# Generated by Django 6.0.7 on 2026-09-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
