# Generated by Django 6.0.7 on 2026-07-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_tareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='realizada',
            field=models.BooleanField(default=False),
        ),
    ]
