# Generated by Django 6.0.7 on 2026-07-27 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_tareas_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='pataton',
        ),
        migrations.AddField(
            model_name='tareas',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'En Proceso'), ('COM', 'Completada')], default='PEN', max_length=3),
        ),
        migrations.AddField(
            model_name='tareas',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tareas',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tareas',
            name='prioridad',
            field=models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta')], default='M', max_length=1),
        ),
    ]
