# Generated by Django 6.0.7 on 2026-07-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_tareas_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='tareas_imagenes/'),
        ),
    ]
