# Generated by Django 6.0.7 on 2026-07-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_comentario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='tiempo_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tiempo estimado en horas (ej. 2.5)', max_digits=5),
        ),
        migrations.AddField(
            model_name='tareas',
            name='tiempo_trabajado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tiempo real trabajado en horas (ej. 1.0)', max_digits=5),
        ),
    ]
