# Generated by Django 6.0.7 on 2026-07-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_tareas_tiempo_estimado_tareas_tiempo_trabajado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='inicio_trabajo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
