# Generated by Django 6.0.7 on 2026-09-02 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0013_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='miapp.categoria'),
        ),
    ]
